### ISSUE TITLE
number of designs

### ISSUE THREAD

**Issue by phongnq94** [martinpacesa/BindCraft#158]
Hello,

After finishing the slurm job, I only get 95 accepted pdb instead of 100 as I requested in the setting_target file. 

I checked the log file of the slurm job and see "Target number 100 of designs reached! Reranking...". In Ranked folder of the output I also can see 95 pdbs. 

What is the reason I didn't have 100 designs after the run?

Best,
Phong

**Comment by martinpacesa** [comment]
Perhaps there are hidden files with the extension .pdb in your folder?

**Comment by phongnq94** [comment]
> Perhaps there are hidden files with the extension .pdb in your folder?

I just tried to use "ls -a /my/output/folder/Accepted/*.pdb | wc -l" but the number is still the same. 
Also in the rank folder there are only rank 1 to 95.

**Comment by martinpacesa** [comment]
Interesting, it must be some ghost files though that don't show up. Can you try replacing this line in colabdesign_utils.py:

accepted_binders = [f for f in os.listdir(design_paths["Accepted"]) if f.endswith('.pdb')]

with:

accepted_binders = [f for f in os.listdir(design_paths["Accepted"]) if f.endswith('.pdb') and os.path.isfile(os.path.join(design_paths["Accepted"], f))]

**Comment by phongnq94** [comment]
> Interesting, it must be some ghost files though that don't show up. Can you try replacing this line in generic_utils.py:
> 
> accepted_binders = [f for f in os.listdir(design_paths["Accepted"]) if f.endswith('.pdb')]
> 
> with:
> 
> accepted_binders = [f for f in os.listdir(design_paths["Accepted"]) if f.endswith('.pdb') and os.path.isfile(os.path.join(design_paths["Accepted"], f))]

Thank you Martin. 
The issue was solved with this change in generic_utils.py.

**Comment by phongnq94** [comment]
Hi again, 

It seems that the issue was not solve.

I ran few other small test jobs again with "number_of_final_designs": 10. In one of them, BindCraft gave me 6 accepted design in the Accepted folder and Ranked folder. 

When I checked the end of the slurm file log, here is the end it:
"Target number 12 of designs reached! Reranking..."

So now the final numbers of designs in Accepted folder is not correct, and also the target number of designs reached in slurm log is not correct neither? 

The problem also occur randomly in different jobs. I'm wonder if it is causing by something wrong with the installation? I'm using hpc.

**Comment by dgokduman** [comment]
ndCraft keeps showing “Accepted Designs = 0” no matter what I do. This happens with many PDB files I’ve tried, even when I don’t specify any target hotspot residues. I’ve also tried editing the structure — like downloading only specific domains — but nothing seems to work. For example, I’ve used PDBs like 5m5e and 2erj (without chain A), but I still get zero accepted designs. What should I do? Please help.

**Comment by dgokduman** [comment]
BindCraft keeps showing “Accepted Designs = 0” no matter what I do. This happens with many PDB files I’ve tried, even when I don’t specify any target hotspot residues. I’ve also tried editing the structure — like downloading only specific domains — but nothing seems to work. For example, I’ve used PDBs like 5m5e and 2erj (without chain A), but I still get zero accepted designs. What should I do? Please help.

**Comment by mofatuzi** [comment]
> BindCraft keeps showing “Accepted Designs = 0” no matter what I do. This happens with many PDB files I’ve tried, even when I don’t specify any target hotspot residues. I’ve also tried editing the structure — like downloading only specific domains — but nothing seems to work. For example, I’ve used PDBs like 5m5e and 2erj (without chain A), but I still get zero accepted designs. What should I do? Please help.

Try to change "predict_initial_guess " setting to true in "settings_advanced/default_4stage_multimer.json"
